# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-DE-NetBank
version:      1.05_01
version_from: lib/Finance/Bank/DE/NetBank.pm
installdirs:  site
requires:
    Class::Accessor:               0.22
    Net::SSLeay:                   1.25
    Text::CSV_XS:                  0.23
    WWW::Mechanize:                1.16

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
