# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-DE-NetBank
version:      1.00
version_from: lib/Finance/Bank/DE/NetBank.pm
installdirs:  site
requires:
    base:                          0
    Class::Accessor:               0
    Encode:                        0
    HTML::TreeBuilder:             0
    Text::CSV_XS:                  0
    WWW::Mechanize:                0.43

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
